language: minimal
service: docker
env:
  - image=perl:5.16
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - docker run --init -it -v $PWD:/$TRAVIS_REPO_SLUG -w /$TRAVIS_REPO_SLUG $image ./test
